theme = "mytheme"

[editor]
bufferline="multiple"

[editor.soft-wrap]
enable = true

[editor.cursor-shape]
insert = "bar"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]