theme = "dark_plus"

[editor]
bufferline="multiple"
lsp.display-inlay-hints=true

[editor.soft-wrap]
enable = true

[editor.cursor-shape]
insert = "bar"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]